---
- name: Deploy RaviShop AI to EC2
  hosts: app_servers
  become: yes

  vars_files:
    - ../vars/secrets.yml

  roles:
    - docker
    - app

  post_tasks:
    - name: Wait for app to be healthy
      uri:
        url: "http://{{ ansible_host }}:5000/health"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 10
      delay: 5

    - name: Print success message
      debug:
        msg: "RaviShop AI deployed successfully!"
